// <auto-generated />
using System;
using APIPontoColaborador.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIPontoColaborador.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("APIPontoColaborador.Models.Cargo", b =>
                {
                    b.Property<int>("CargoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DescricaoCargo")
                        .HasColumnType("longtext");

                    b.HasKey("CargoId");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("APIPontoColaborador.Models.Equipe", b =>
                {
                    b.Property<int>("EquipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Funcionario_FuncionarioId")
                        .HasColumnType("int");

                    b.Property<int?>("FuncionariosFuncionarioId")
                        .HasColumnType("int");

                    b.Property<int>("Lideranca_LiderancaId")
                        .HasColumnType("int");

                    b.Property<int?>("LiderancasLiderancaId")
                        .HasColumnType("int");

                    b.HasKey("EquipeId");

                    b.HasIndex("FuncionariosFuncionarioId");

                    b.HasIndex("LiderancasLiderancaId");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("APIPontoColaborador.Models.Funcionario", b =>
                {
                    b.Property<int>("FuncionarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CargoId")
                        .HasColumnType("int");

                    b.Property<string>("CelularFuncionario")
                        .HasColumnType("longtext");

                    b.Property<string>("Cpf")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataDeAdmissao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailFuncionario")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NascimentoFuncionario")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeDoFuncionario")
                        .HasColumnType("longtext");

                    b.HasKey("FuncionarioId");

                    b.HasIndex("CargoId");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("APIPontoColaborador.Models.Lideranca", b =>
                {
                    b.Property<int>("LiderancaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DescricaoEquipe")
                        .HasColumnType("longtext");

                    b.Property<int>("Funcionario_FuncionarioId")
                        .HasColumnType("int");

                    b.Property<int?>("FuncionariosFuncionarioId")
                        .HasColumnType("int");

                    b.HasKey("LiderancaId");

                    b.HasIndex("FuncionariosFuncionarioId");

                    b.ToTable("Liderancas");
                });

            modelBuilder.Entity("APIPontoColaborador.Models.Ponto", b =>
                {
                    b.Property<int>("PontoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHorarioPonto")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Funcionario_FuncionarioId")
                        .HasColumnType("int");

                    b.Property<int?>("FuncionariosFuncionarioId")
                        .HasColumnType("int");

                    b.Property<string>("Justificativa")
                        .HasColumnType("longtext");

                    b.HasKey("PontoId");

                    b.HasIndex("FuncionariosFuncionarioId");

                    b.ToTable("Pontos");
                });

            modelBuilder.Entity("APIPontoColaborador.Models.Equipe", b =>
                {
                    b.HasOne("APIPontoColaborador.Models.Funcionario", "Funcionarios")
                        .WithMany()
                        .HasForeignKey("FuncionariosFuncionarioId");

                    b.HasOne("APIPontoColaborador.Models.Lideranca", "Liderancas")
                        .WithMany()
                        .HasForeignKey("LiderancasLiderancaId");

                    b.Navigation("Funcionarios");

                    b.Navigation("Liderancas");
                });

            modelBuilder.Entity("APIPontoColaborador.Models.Funcionario", b =>
                {
                    b.HasOne("APIPontoColaborador.Models.Cargo", "Cargos")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargos");
                });

            modelBuilder.Entity("APIPontoColaborador.Models.Lideranca", b =>
                {
                    b.HasOne("APIPontoColaborador.Models.Funcionario", "Funcionarios")
                        .WithMany()
                        .HasForeignKey("FuncionariosFuncionarioId");

                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("APIPontoColaborador.Models.Ponto", b =>
                {
                    b.HasOne("APIPontoColaborador.Models.Funcionario", "Funcionarios")
                        .WithMany()
                        .HasForeignKey("FuncionariosFuncionarioId");

                    b.Navigation("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
